class HappyMethodless
{
    // No structure
    public static void main(String[] args) 
    {
        System.out.println("It might seem crazy what I'm about to say");
        System.out.println("Sunshine she's here, you can take away");
        System.out.println("I'm a hot air balloon, I could go to space");
        System.out.println("With the air, like I don't care baby by the way");
        System.out.println();
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
        System.out.println();
        System.out.println("Here come bad news talking this and that");
        System.out.println("Yeah, give me all you got, don't hold back");
        System.out.println("Yeah, well I should probably warn you I'll be just fine");
        System.out.println("Yeah, no offense to you don't waste your time");
        System.out.println("Here's why");
        System.out.println("");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
        System.out.println("");
        System.out.println("Happy, bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("Love is too happy to bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("I said bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("Love is too happy to bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("I said");
        System.out.println();
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
        System.out.println();
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
        System.out.println();
        System.out.println("Happy, bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("Love is too happy to bring me down");
        System.out.println("Can't nothing, bring me down");
        System.out.println("I said");
        System.out.println();
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
        System.out.println();
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like a room without a roof");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like happiness is the truth");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you know what happiness is to you");
        System.out.println("Because I'm happy");
        System.out.println("Clap along if you feel like that's what you wanna do");
    }
}
